### ISSUE TITLE
watched folder ?

### ISSUE THREAD

**Issue by MoonshineSG** [OctoPrint/OctoPrint-Autoselect#1]
If files get uploaded via "watched" folder the auto-select doesn't get triggered. since watched foder is used mainly for automated workflow, it only makes sense to have the latest file auto selected...

**Comment by foosel** [comment]
That is not possible with current stable versions of OctoPrint since only an actual file upload triggers a notification within the system.

I'll look into adding some more ways into OctoPrint for plugins to get notified of file interactions in order to allow for more flexibility here, but until that is done it only works with uploaded files. If you are running windows on your client there's also [OctoWatcher](https://github.com/TwystNeko/OctoWatcher) that might be of interest to solve that workflow until then.

**Comment by foosel** [comment]
See foosel/OctoPrint#1092

**Comment by MoonshineSG** [comment]
I am using raspberry pi. I could of course implement my own folder watch... or wait until you find a more generic solution... 
thanks.

**Comment by foosel** [comment]
I meant as the "source" of the files. E.g. if you generate your gcode files on a windows PC, you could save them into a folder watched by the above linked tool instead of into the (mounted) watched folder from the actual OctoPrint install.

**Comment by MoonshineSG** [comment]
i do smth similar. I use mac, so I have Hazel (an automation tool) to watch a folder for new gcode and sftp it into the octopi "watch" folder... I guess I could call the octopi upload API instead...

**Comment by MoonshineSG** [comment]
I changed my upload command from sftp to curl

`curl -H "Content-Type: multipart/form-data" -H "X-Api-Key: WHATEVERMYKEYIS"  -F "select=true" -F "print=false" -F "file=@$1" http://X.X.X.X/api/files/local`

hazel replaces $1 with the gcode file name on the watched folder on my mac ... and done! Upload and select. I could even start printing immediately. 

This is what can be done when an app has a robust API to call... One of the reasons why I love Octoprint!

**Comment by foosel** [comment]
:+1: :)
