### ISSUE TITLE
Detection of currently running print is broken

### ISSUE THREAD

**Issue by Kunsi** [OctoPrint/OctoPrint-Autoselect#2]
The Plugin tries to autoselect an uploaded file regardless of printer state. Octoprint itself forbids loading new files when printing, however I think this should be fixed inside the plugin, and should not rely on OctoPrints behaviour.

Log:
`2017-03-05 19:51:49,875 - octoprint.plugins.autoselect - INFO - Selecting Druckerteile/filament_guide.gcode on local that was just uploaded
2017-03-05 19:51:49,876 - octoprint.printer.standard - INFO - Cannot load file: printer not connected or currently busy`

**Comment by foosel** [comment]
Actually [this line](https://github.com/OctoPrint/OctoPrint-Autoselect/blob/master/octoprint_autoselect/__init__.py#L12) should prevent exactly that. However it looks like there is a bug in OctoPrint because `is_ready` is not behaving according to the documentation here. I'll have to fix that in OctoPrint.

**Comment by foosel** [comment]
That should be fixed in OctoPrint 1.3.3, which was just released.
